# -*- coding: utf-8 -*-
"""Team chest x-ray AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDYD7hBJ8SlQT0AvljuI9bt_MEQl2Sta

# CHEST X-RAY AI

STREAMLIT CODE
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install streamlit pyngrok

from pyngrok import ngrok
ngrok.set_auth_token("35xehyU4lwiKFWCOk4waESUeiqP_2y5miUPxc8UQ4nxi9uvMy")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# import cv2
# from PIL import Image
# import time
# 
# 
# # Sidebar: Team Info
# 
# st.sidebar.title("Team Info")
# team_name = st.sidebar.text_input("Enter your team name:", "DeepTech Team Chest-xray AI Team")
# st.sidebar.write(f"Team: **{team_name}**")
# 
# 
# # Load trained model (cached)
# 
# @st.cache_resource
# def load_xray_model():
#     return tf.keras.models.load_model('/content/drive/MyDrive/hackathon/model.keras')
# 
# model = load_xray_model()
# labels = ["Normal", "Pneumonia"]
# colors = {"Normal": "green", "Pneumonia": "red"}
# 
# 
# # SVD Preprocessing
# 
# def apply_svd(img_gray, k=40):
#     img_gray = img_gray.astype(np.float32) / 255.0
#     U, S, Vt = np.linalg.svd(img_gray, full_matrices=False)
#     img_svd = np.dot(np.dot(U[:, :k], np.diag(S[:k])), Vt[:k, :])
#     img_svd = np.clip(img_svd, 0, 1)
#     img_svd = (img_svd * 255).astype(np.uint8)
#     return img_svd
# 
# 
# # Main Interface
# 
# st.title("DeepTech Chest-Xray AI 🩺 (SVD + XAI)")
# uploaded = st.file_uploader("Upload Lung X-ray", ["png","jpg","jpeg"])
# 
# if uploaded:
#     # Load image and preprocess
#     img = Image.open(uploaded).convert("L")
#     img = np.array(img)
#     img = cv2.resize(img, (224,224))
#     img_svd = apply_svd(img, k=40)
# 
#     x_input = img_svd.astype(np.float32)/255.0
#     x_input = np.expand_dims(x_input, (0,-1))
# 
#     # Model prediction
#     pred = model.predict(x_input)[0]
#     class_idx = int(pred.argmax())
#     confidence = float(pred.max())
#     pred_label = labels[class_idx]
# 
#     # Display images
#     st.image(img, caption="Original Image", use_container_width=True)
#     st.image(img_svd, caption="SVD Processed", use_container_width=True)
# 
#     # Colored prediction box
#     st.markdown(f"<h2 style='color:{colors[pred_label]};'>Prediction: {pred_label}</h2>", unsafe_allow_html=True)
# 
#     # Confidence Bar
#     st.write("**Confidence:**")
#     st.progress(confidence)
# 
#     # Confetti if Normal
#     if pred_label == "Normal":
#         st.balloons()
# 
# 
#     # Chatbox: Explain AI result
# 
#     st.write("### 💬 Explain result ")
#     if st.button("Explain AI Decision"):
#         with st.spinner("AI is analyzing the scan..."):
#             time.sleep(1.5)
#         simple_exp = (
#             f"The AI predicts **{pred_label}** "
#             f"with **{confidence*100:.1f}% confidence**.\n\n"
#             "The image was compressed using **SVD** to focus on key patterns. "
#             "A CNN then analyzed the lungs for infection signs. \n\n"
#             "⚠️ This is AI interpretation only and not medical advice."
#         )
#         st.write(simple_exp)
#

!pip install pyngrok
from pyngrok import ngrok
import os

# Set your token
NGROK_TOKEN = "35xehyU4lwiKFWCOk4waESUeiqP_2y5miUPxc8UQ4nxi9uvMy"
os.environ["NGROK_AUTH_TOKEN"] = NGROK_TOKEN
ngrok.set_auth_token(NGROK_TOKEN)

print("Ngrok installed and token set ")

!ngrok authtoken 35xehyU4lwiKFWCOk4waESUeiqP_2y5miUPxc8UQ4nxi9uvMy

from pyngrok import ngrok
import os

# Kill any previous tunnels
ngrok.kill()

# Run Streamlit app in background
os.system("streamlit run app.py &")

# Create public URL
public_url = ngrok.connect(8501)
print("Your public Streamlit URL:", public_url)