# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwWB8AITvOmdJWyV8flLvukV9aVQGq-F

# CHEST X-RAY AI

STREAMLIT CODE
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image
import time
import gdown
import os

# Sidebar
st.sidebar.title("🧬 Team Chest X-ray AI")
st.sidebar.subheader("👥 Team Members")
st.sidebar.write("- **Maryam Ibrahim Hamza**")
st.sidebar.write("- **Saratu Banau Salihu**")
st.sidebar.markdown("---")
st.sidebar.write("🌍 *Nigeria Hackathon 2025*")

# Download model (only once)
MODEL_URL = "https://drive.google.com/uc?id=1gzOhv1qfBwTto2hNkVnFHyiK3tLWsCoV"
MODEL_PATH = "model.keras"

if not os.path.exists(MODEL_PATH):
    with st.spinner("⬇️ Downloading AI model... please wait"):
        gdown.download(MODEL_URL, MODEL_PATH, quiet=False)

# Load model
@st.cache_resource
def load_model(path):
    return tf.keras.models.load_model(path)

model = load_model(MODEL_PATH)
labels = ["Normal", "Pneumonia"]

# SVD
def apply_svd(img_gray, k=40):
    img_gray = img_gray.astype(np.float32)/255.0
    U, S, Vt = np.linalg.svd(img_gray, full_matrices=False)
    img_svd = U[:, :k] @ np.diag(S[:k]) @ Vt[:k, :]
    img_svd = np.clip(img_svd, 0, 1)
    return (img_svd*255).astype(np.uint8)

# UI
st.title("🩺 Chest X-ray Diagnosis Assistant (SVD + Explainable AI)")
uploaded = st.file_uploader("Upload Lung X-ray Image", ["png","jpg","jpeg"])

if uploaded:
    img = Image.open(uploaded).convert("L")
    img = np.array(img)
    img = cv2.resize(img, (224,224))
    img_svd = apply_svd(img, k=40)

    x = img_svd.astype(np.float32)/255.0
    x = np.expand_dims(x, (0,-1))

    pred = model.predict(x)[0]
    idx = int(pred.argmax())
    conf = float(pred.max())

    # Show results
    col1, col2 = st.columns(2)
    col1.image(img, caption="Original Scan", use_container_width=True)
    col2.image(img_svd, caption="AI Optimized (SVD)", use_container_width=True)

    st.markdown(f"### ✅ **Result: `{labels[idx]}`**")
    st.progress(conf)
    st.info(f"🧪 AI Confidence: **{conf*100:.2f}%**")

    st.markdown("---")

    # Explanation button
    if st.button("💬 Explain AI Decision"):
        with st.spinner("Analyzing important lung patterns..."):
            time.sleep(1.2)
        st.write(
            f"The AI believes this X-ray shows **{labels[idx]}** because it detected "
            f"patterns commonly linked to **lung condition indicators** after compressing "
            f"the image using **SVD** to keep only the strongest signals."
        )
        st.write("⚠️ This is not a doctor's diagnosis, it's AI assistance to explain the scan.")

import sys

if 'google.colab' in sys.modules:
    !pip install streamlit opencv-python gdown

import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image
import time
import gdown  # ✅ allowed on Streamlit Cloud

# -----------------------------
# Sidebar: Team Info
# -----------------------------
st.sidebar.title("🧠 Team Chest X-ray AI")
st.sidebar.markdown("### 🔬 Members:")
st.sidebar.write("👩‍💻 Maryam Ibrahim Hamza")
st.sidebar.write("👩‍💻 Saratu Banau Salihu")

# -----------------------------
# Download & Load Model (cached)
# -----------------------------
@st.cache_resource
def load_xray_model():
    model_path = "model.keras"

    # ✅ Direct download from Google Drive
    gdown.download(id="1gzOhv1qfBwTto2hNkVnFHyiK3tLWsCoV", output=model_path, quiet=False)

    # ✅ Load the model
    return tf.keras.models.load_model(model_path)

model = load_xray_model()
labels = ["Normal", "Pneumonia"]
colors = {"Normal": "green", "Pneumonia": "red"}

# -----------------------------
# SVD Preprocessing Function
# -----------------------------
def apply_svd(img_gray, k=40):
    img_gray = img_gray.astype(np.float32) / 255.0
    U, S, Vt = np.linalg.svd(img_gray, full_matrices=False)
    img_svd = U[:, :k] @ np.diag(S[:k]) @ Vt[:k, :]
    img_svd = np.clip(img_svd, 0, 1)
    return (img_svd * 255).astype(np.uint8)

# -----------------------------
# Main UI
# -----------------------------
st.title("DeepTech Chest-Xray AI 🩺 (SVD + XAI)")
uploaded = st.file_uploader("Upload Lung X-ray", ["png", "jpg", "jpeg"])

if uploaded:
    # ✅ Read image and resize
    img = Image.open(uploaded).convert("L")
    img_np = np.array(img)
    img_resized = cv2.resize(img_np, (224, 224))

    # ✅ Apply SVD
    img_svd = apply_svd(img_resized, k=40)

    # ✅ Prepare for model input
    x_input = (img_svd.astype(np.float32) / 255.0)[None, ..., None]

    # ✅ Prediction
    pred = model.predict(x_input)[0]
    pred_label = labels[pred.argmax()]
    confidence = float(pred.max())

    # ✅ Display images
    st.image(img_resized, caption="Original Image", use_container_width=True)
    st.image(img_svd, caption="SVD Processed", use_container_width=True)

    # ✅ Prediction result box
    st.markdown(
        f"<h2 style='color:{colors[pred_label]};text-align:center;'>🧪 Prediction: {pred_label}</h2>",
        unsafe_allow_html=True,
    )

    # ✅ Confidence
    st.write("### 📊 Confidence Score")
    st.progress(confidence)
    st.write(f"**{confidence * 100:.2f}%**")

    if pred_label == "Normal":
        st.balloons()

    # ✅ Explainability chatbox button
    st.write("### 💬 Need explanation?")
    if st.button("Click for AI insight 🧠"):
        with st.spinner("AI is reviewing the scan patterns..."):
            time.sleep(1.5)
        st.write(
            f"🩻 The AI detected **{pred_label} lung patterns** with "
            f"**{confidence * 100:.1f}% confidence**.\n\n"
            "To improve accuracy, **SVD compression** kept key infection structures "
            "before the **CNN analyzed** possible pneumonia signs.\n\n"
            "⚠️ This is AI interpretation, not medical advice."
        )